# Generated by Django 5.1.5 on 2025-02-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecity',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favoritecity',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
