# Generated by Django 5.1.5 on 2025-02-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_favoritecity_country_favoritecity_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='favoritecity',
            name='region',
        ),
    ]
